---
openapi: 3.0.1
info:
  title: ReadonlyREST
  description: 'This si internal ReadonlyREST API specification'
  termsOfService: http://swagger.io/terms/
  version: 1.0.5
externalDocs:
  description: Find out more about ROR
  url: https://readonlyrest.com/
servers:
- url: http://localhost:9200
paths:
  /_readonlyrest/admin/config/load:
    get:
      tags:
      - cluster config
      summary: gets ror config from all ror nodes
      operationId: rorClusterConfig
      parameters:
      - name: timeout
        in: query
        description: timeout for reach node to prepare response
        examples:
          one minute:
            value: 1m
            description: 1 minute
          one minute too:
            value: 60s
            description: 60 seconds
          very long:
            value: 1d
            description one day
          very short:
            value: 100nanos
            description: 100 nanoseconds
        schema:
          type: string
          format: time-unit
          pattern: \d+(d|h|m|s|ms|micros|nanos)
      responses:
        200:
          description: Your request has been proceed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigSummary'
components:
  schemas:
    ConfigSummary:
      type: object
      properties:
        config:
          type: number
          format: int32
        warnings:
          type: object
        error:
          type: string
          description: If node couldn't produce response, there is error message.
    Warning:
      type: object
      oneOf:
      - $ref: '#/components/schemas/Warning.NodeReturnedConfigError'
    Warning.NodeReturnedConfigError:
      type: object
      properties:
        nodeId:
          type: string
        error:
          type: string
